# Generated by Django 4.1.2 on 2022-10-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text="Enter the book's natural language (e.g. English, French, Japanese, etc.)", to='catalog.language'),
        ),
    ]
