# Generated by Django 4.1.2 on 2022-10-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_fof_death',
            new_name='date_of_death',
        ),
    ]
